plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
var modules = ['base', 'client_events', 'common', 'config', 'core', 'data', 'extensions', 'fluids',
            'lazy_registration', 'level_events', 'model_builders', 'tags']

base {
	archivesName = project.archives_base_name
}

loom {
	accessWidenerPath = project.file("src/main/resources/oreganized.accesswidener")
	runs {
		datagen {
			inherit client
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated")}"
			vmArg "-Dfabric-api.datagen.modid=oreganized"
			vmArg "-Dporting_lib.datagen.existing_resources=${file("src/main/resources")}"

			runDir "build/datagen"
		}
	}
}

sourceSets {
	main {
		resources {
			srcDirs += [
					'src/generated'
			]
			exclude ".cache/**"
		}
	}
}

repositories {
	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
	}
	maven {
		name = 'Quilt'
		url = "https://maven.quiltmc.org/repository/release/"
	}
	maven {
		name = "DevOS"
		url = "https://mvn.devos.one/releases/"
	}

	maven {
		name = "JamiesWhiteShirt"
		url = "https://maven.jamieswhiteshirt.com/libs-release"
		content {
			includeGroup "com.jamieswhiteshirt"
		}
	}

	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}

	maven {
		name = "Greenhouse Maven"
		url = 'https://maven.greenhouseteam.dev/releases/'
	}

	maven {
		url "https://jitpack.io/" // Fabric ASM
		content {
			excludeGroup "io.github.fabricators_of_create"
		}
	}
	maven {
		name = "sappho company"
		url = "https://maven.is-immensely.gay/releases"
	}

	mavenCentral()
}

fabricApi {
	configureDataGeneration() {
		createRunConfiguration = false
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		mappings("org.quiltmc:quilt-mappings:${project.minecraft_version}+build.${project.qm_version}:intermediary-v2")
		parchment("org.parchmentmc.data:parchment-${project.parchment_version}@zip")
		officialMojangMappings()
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Dependencies
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation include("uwu.serenity.cam:CustomArmorModels-fabric:${project.custom_armor_version}")


	for(port_lib in modules) {
		modImplementation include("io.github.fabricators_of_create.Porting-Lib:${port_lib}:${project.port_lib_version}")
	}

	modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")

	modCompileOnly("maven.modrinth:detail-armor-bar:${project.detailab_version}")
	modCompileOnly("maven.modrinth:nethers-delight-refabricated:${project.nd_version}")
	modCompileOnly("vectorwing:FarmersDelight:${project.fd_version}") {
		exclude(group: "net.fabricmc")
	}

	if(project.test_mods == "true") {
		modLocalRuntime("maven.modrinth:detail-armor-bar:${project.detailab_version}")
		modLocalRuntime("maven.modrinth:nethers-delight-refabricated:${project.nd_version}")
		modLocalRuntime("vectorwing:FarmersDelight:${project.fd_version}") {
				exclude(group: "net.fabricmc")
		}
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			name "sapphoCompany"
			url "https://maven.is-immensely.gay/nightly"
			credentials(org.gradle.api.credentials.PasswordCredentials)
			authentication {
				basic(BasicAuthentication)
			}
		}
	}
}
