# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.15.0
parchment_version=1.20.1:2023.09.03
qm_version=23



# Mod Properties
mod_version=2.0.3d-fabric
maven_group=galena
archives_base_name=Oreganized

# Dependencies
fabric_version=0.90.0+1.20.1
port_lib_version=2.3.4+1.20.1
custom_armor_version=1.2d+1.20.1
modmenu_version=7.2.2

#Integrations
detailab_version=2.6.3+1.20.1-fabric
fd_version=1.20.1-2.1.1+refabricated
nd_version=1.20.1-4.1.1
test_mods=true
